name: 'Test SwiftPM with xccov'
author: 'jemmons'
description: 'Build and test a Swift Package, generating coverage.json'
inputs:
  package:
    descrition: 'name of package'
    required: true
outputs:
  path:
    description: 'The path of coverage.json'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'orange'
