name: 'Generate xccov json'
author: 'jemmons'
description: 'Generate json coverage information with xccov.'
inputs:
  resultfile:
    descrition: 'filepath of .xcresults'
    required: true
  outputpath:
    description: 'filepath for json output'
    required: true
  targets:
    description: 'space-seperated list of targets to output (all others will be removed)'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'orange'
